apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-trigger
  labels:
    app: tekton-trigger
spec:
  replicas: 1
  template:
    metadata:
      name: tekton-trigger
      labels:
        app: tekton-trigger
    spec:
      serviceAccountName: argo-events-sa
      containers:
        - name: tekton-trigger
          image: metalgearsolid/tekton-trigger:v0.1.0
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: tekton-trigger
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-trigger
spec:
  selector:
    app: tekton-trigger
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer
