apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: example
  namespace: tekton-pipelines
spec:
  pipelineSpec:
    tasks:
      - name: echo-good-morning
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
